# "name":  Name of the store
# "day":   Days the store are open
# "halal": Is store halal or not
# "wtime": 3 values. Each is the mean sample value of separate observation samples taken, one done by each group member
# "btime": Time breakfast menu is available
# "ltime": Time lunch menu is available
# "dtime": Time dinner menu is available
# "time":  Store's operating hours

# "breakfast", "lunch", "dinner": List of tuples. (menuitem, price)
# "closed" : Message to display when store is closed



# BOON JUEY (DATA STRUCTURE)
# CHENG YUN (OPERATING TIME AND DAY)
# IRVIN (STORE MENU ITEMS, AND PRICE)
can1 = {
              "name" : "Mini Wok",
              "day"  : ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
              "halal": False,
              "wtime": [1.5,2.5,2],
              "btime": [700, 1159],
              "ltime": [1200, 1429],
              "dtime": [1430, 1700],
              "time" : [700, 1700],
              "breakfast": [("Sambal Chicken Fried Rice" , 3.80),
                            ("Salted Fish Fried Rice" , 3.80),
                            ("Fried Rice with Prawn" , 3.80),
                            ("Fried Rice with Fillet" , 3.80),
                            ("Chicken Fried Rice" , 3.80),
                            ("Ginger & Onion Pork Rice" , 4.50),
                            ("Kung Bao Chicken Rice" , 4.20),
                            ("Black Pepper Chicken Rice" , 4.20),
                            ("Ginger & Onion Chicken Rice" , 4.20),
                            ("Pan Fried Chicken Rice" , 4.20),
                            ("Ginger & Onion Fish Fillet Rice" , 4.20),
                            ("Sweet & Sour Fish Fillet Rice" , 4.20),
                            ("Sambal Fish Fillet Rice" , 4.20),
                            ("Mixed Veg Toufu" , 4.00),
                            ("Fried Beef Hor Fun" , 4.80),
                            ("Seafood Ee Mee" , 3.80),
                            ("Seafood Hor Fun" , 3.80),
                            ("Beef Fried Rice" , 4.80),
                            ("Seafood Bee Hoon" , 3.80),
                            ("Fried Seafood Hor Fun" , 3.80),
                            ("Sambal Long Bean w/ Pork" , 4.50),
                            ("Ginger & Onion Beef Rice" , 4.80),
                            ("Seafood Hokkien Mee" , 3.80),
                            ("Beef Hor Fun" , 4.80),
                            ("Black Pepper Pork Rice" , 4.50),
                            ("Black Pepper Beef Rice" , 4.80)],

              "lunch":      [("Sambal Chicken Fried Rice" , 3.80),
                            ("Salted Fish Fried Rice" , 3.80),
                            ("Fried Rice with Prawn" , 3.80),
                            ("Fried Rice with Fillet" , 3.80),
                            ("Chicken Fried Rice" , 3.80),
                            ("Ginger & Onion Pork Rice" , 4.50),
                            ("Kung Bao Chicken Rice" , 4.20),
                            ("Black Pepper Chicken Rice" , 4.20),
                            ("Ginger & Onion Chicken Rice" , 4.20),
                            ("Pan Fried Chicken Rice" , 4.20),
                            ("Ginger & Onion Fish Fillet Rice" , 4.20),
                            ("Sweet & Sour Fish Fillet Rice" , 4.20),
                            ("Sambal Fish Fillet Rice" , 4.20),
                            ("Mixed Veg Toufu" , 4.00),
                            ("Fried Beef Hor Fun" , 4.80),
                            ("Seafood Ee Mee" , 3.80),
                            ("Seafood Hor Fun" , 3.80),
                            ("Beef Fried Rice" , 4.80),
                            ("Seafood Bee Hoon" , 3.80),
                            ("Fried Seafood Hor Fun" , 3.80),
                            ("Sambal Long Bean w/ Pork" , 4.50),
                            ("Ginger & Onion Beef Rice" , 4.80),
                            ("Seafood Hokkien Mee" , 3.80),
                            ("Beef Hor Fun" , 4.80),
                            ("Black Pepper Pork Rice" , 4.50),
                            ("Black Pepper Beef Rice" , 4.80)],

              "dinner":     [("Sambal Chicken Fried Rice" , 3.80),
                            ("Salted Fish Fried Rice" , 3.80),
                            ("Fried Rice with Prawn" , 3.80),
                            ("Fried Rice with Fillet" , 3.80),
                            ("Chicken Fried Rice" , 3.80),
                            ("Ginger & Onion Pork Rice" , 4.50),
                            ("Kung Bao Chicken Rice" , 4.20),
                            ("Black Pepper Chicken Rice" , 4.20),
                            ("Ginger & Onion Chicken Rice" , 4.20),
                            ("Pan Fried Chicken Rice" , 4.20),
                            ("Ginger & Onion Fish Fillet Rice" , 4.20),
                            ("Sweet & Sour Fish Fillet Rice" , 4.20),
                            ("Sambal Fish Fillet Rice" , 4.20),
                            ("Mixed Veg Toufu" , 4.00),
                            ("Fried Beef Hor Fun" , 4.80),
                            ("Seafood Ee Mee" , 3.80),
                            ("Seafood Hor Fun" , 3.80),
                            ("Beef Fried Rice" , 4.80),
                            ("Seafood Bee Hoon" , 3.80),
                            ("Fried Seafood Hor Fun" , 3.80),
                            ("Sambal Long Bean w/ Pork" , 4.50),
                            ("Ginger & Onion Beef Rice" , 4.80),
                            ("Seafood Hokkien Mee" , 3.80),
                            ("Beef Hor Fun" , 4.80),
                            ("Black Pepper Pork Rice" , 4.50),
                            ("Black Pepper Beef Rice" , 4.80)],

              "closed": [
                           ("This store is not open at this moment.\nWe apologise for any inconvenience caused.", "")
                        ]
        }


can2 = {
              "name" : "Mala Hot Pot",
              "day"  : ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
              "halal": False,
              "wtime": [6,3,6],
              "btime": [700, 1159],
              "ltime": [1200, 1429],
              "dtime": [1430, 1700],
              "time" : [700, 1700],
              "breakfast": [("Plain Rice" , 0.50),
                            ("Vegetable A (100 grams)" , 1.20),
                            ("Vegetable B (100 grams)" , 1.40),
                            ("Meat (100 grams)" , 1.80),
                            ("Seafood (100 grams)" , 2.30)],

              "lunch":     [("Plain Rice" , 0.50),
                            ("Vegetable A (100 grams)" , 1.20),
                            ("Vegetable B (100 grams)" , 1.40),
                            ("Meat (100 grams)" , 1.80),
                            ("Seafood (100 grams)" , 2.30)],

              "dinner":    [("Plain Rice" , 0.50),
                            ("Vegetable A (100 grams)" , 1.20),
                            ("Vegetable B (100 grams)" , 1.40),
                            ("Meat (100 grams)" , 1.80),
                            ("Seafood (100 grams)" , 2.30)],

              "closed": [
                           ("This store is not open at this moment.\nWe apologise for any inconvenience caused.", "")
                        ]
        }

can3 = {
              "name" : "McDonald's",
              "day"  : ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
              "halal": True,
              "wtime": [2.5,1.5,3.5],
              "btime": [700, 1159],
              "ltime": [1200, 1759],
              "dtime": [1800, 2359],
              "time" : [700, 2359],
              "breakfast": [("Egg White Delight McMuffin", 2.79),
                            ("Egg McMuffin", 2.79),
                            ("Sausage McMuffin with Egg", 2.99),
                            ("Bacon, Egg, and Cheese Biscuit", 3.19),
                            ("Sausage Biscuit with Egg", 2.79),
                            ("Sausage Gravy and Biscuit", 2.89),
                            ("Bacon, Egg, and Cheese McGriddles", 3.29)
                           ],

              "lunch":   [("McFlurry Oreo" , 2.70),
                          ("McFlurry Strawberry" , 3.00),
                          ("Sundae" , 1.70),
                          ("Vanilla Cone" , 0.80),
                          ("Choco Cone" , 1.00),
                          ("Classic Angus Cheese Burger" , 8.95),
                          ("Double Cheeseburger" , 3.50),
                          ("Big Mac" , 5.75),
                          ("The Original Angus" , 6.20),
                          ("McSpicy Single" , 5.25),
                          ("McSpicy Double" , 7.20),
                          ("McWings 4pcs" , 4.20),
                          ("Chicken Nuggets 6pcs" , 4.60),
                          ("Chicken Nuggets 9pcs" , 6.20)],

              "dinner":  [("McFlurry Oreo" , 2.70),
                          ("McFlurry Strawberry" , 3.00),
                          ("Sundae" , 1.70),
                          ("Vanilla Cone" , 0.80),
                          ("Choco Cone" , 1.00),
                          ("Classic Angus Cheese Burger" , 8.95),
                          ("Double Cheeseburger" , 3.50),
                          ("Big Mac" , 5.75),
                          ("The Original Angus" , 6.20),
                          ("McSpicy Single" , 5.25),
                          ("McSpicy Double" , 7.20),
                          ("McWings 4pcs" , 4.20),
                          ("Chicken Nuggets 6pcs" , 4.60),
                          ("Chicken Nuggets 9pcs" , 6.20)],

              "closed": [
                           ("This store is not open at this moment.\nWe apologise for any inconvenience caused.", "")
                        ]
        }

can4 = {
              "name" : "Subway",
              "day"  : ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
              "halal": True,
              "wtime": [3,4.5,4.5],
              "btime": [800, 1159],
              "ltime": [1200, 1429],
              "dtime": [1430, 1700],
              "time" : [800, 1700],
              "breakfast":   [("6-inch Bacon, Egg, and Cheese", 4.00),
                              ("12-inch Bacon, Egg, and Cheese", 5.50),
                              ("6-inch Black Forrest Ham, Egg, and Cheese", 4.00),
                              ("12-inch Bacon, Egg, and Cheese", 5.50),
                              ("6-inch Egg and Cheese Omelette", 4.00),
                              ("12-inch Egg and Cheese Omelette", 5.50),
                              ("6-inch Steak, Egg, and Cheese", 4.00),
                              ("12-inch Steak, Egg, and Cheese", 5.50),
                              ("Hash Browns", 1.10)
                             ],

              "lunch": [("6-inch BLT" , 3.75),
                        ("Footlong BLT" , 5.50),
                        ("6-inch Big Philly Cheesesteak" , 5.50),
                        ("Footlong Big Philly Cheesesteak" , 8.95),
                        ("6-inch Black Forest Ham" , 3.75),
                        ("Footlong Black Forest Ham" , 5.50),
                        ("6-inch Chicken & Bacon Ranch Melt" , 4.75),
                        ("Footlong Chicken & Bacon Ranch Melt" , 7.75),
                        ("6-inch Chipotle Chicken Melt with Guacamole" , 5.00),
                        ("Footlong Chipotle Chicken Melt with Guacamole" , 8.25),
                        ("6-inch Cold Cut Combo" , 3.75),
                        ("Footlong Cold Cut Combo" , 5.50),
                        ("6-inch Italian B.M.T." , 4.25),
                        ("Footlong Italian B.M.T." , 6.75),
                        ("6-inch Steak & Cheese" , 4.75),
                        ("Footlong Steak & Cheese" , 7.75),
                        ("Cookies 1pc" , 0.65),
                        ("Cookies 3pcs" , 1.70),
                        ("Cookies 12pcs" , 6.00),
                        ("Coffee 12oz." , 1.60),
                        ("Coffee 16oz." , 1.80)],

              "dinner":  [("6-inch BLT" , 3.75),
                          ("Footlong BLT" , 5.50),
                          ("6-inch Big Philly Cheesesteak" , 5.50),
                          ("Footlong Big Philly Cheesesteak" , 8.95),
                          ("6-inch Black Forest Ham" , 3.75),
                          ("Footlong Black Forest Ham" , 5.50),
                          ("6-inch Chicken & Bacon Ranch Melt" , 4.75),
                          ("Footlong Chicken & Bacon Ranch Melt" , 7.75),
                          ("6-inch Chipotle Chicken Melt with Guacamole" , 5.00),
                          ("Footlong Chipotle Chicken Melt with Guacamole" , 8.25),
                          ("6-inch Cold Cut Combo" , 3.75),
                          ("Footlong Cold Cut Combo" , 5.50),
                          ("6-inch Italian B.M.T." , 4.25),
                          ("Footlong Italian B.M.T." , 6.75),
                          ("6-inch Steak & Cheese" , 4.75),
                          ("Footlong Steak & Cheese" , 7.75),
                          ("Cookies 1pc" , 0.65),
                          ("Cookies 3pcs" , 1.70),
                          ("Cookies 12pcs" , 6.00),
                          ("Coffee 12oz." , 1.60),
                          ("Coffee 16oz." , 1.80)],

              "closed": [
                           ("This store is not open at this moment.\nWe apologise for any inconvenience caused.", "")
                        ]
        }

can5 = {
              "name" : "Starbucks",
              "day"  : ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
              "halal": True,
              "wtime": [5,4,4.5],
              "btime": [700, 1159],
              "ltime": [1200, 1759],
              "dtime": [1800, 2200],
              "time" : [700, 2200],
              "breakfast": [("Grande Cold Brew" , 5.80),
                            ("Grande Espresso (Single)" , 3.70),
                            ("Grande Caffe Americano" , 5.20),
                            ("Grande Vanilla Sweet Cream Cold Brew" , 7.30),
                            ("Grande Cold Foam Iced Espresso" , 7.30),
                            ("Grande Cappucino" , 6.60),
                            ("Grande Vanilla Latte" , 7.30),
                            ("Grande Earl Grey" , 6.60),
                            ("Grande English Breakfast" , 6.60),
                            ("Grande Chai" , 6.60),
                            ("Grande Iced Shaken Tea Lemonade" , 6.10),
                            ("Grande Caramel Frappuccino" , 7.30),
                            ("Grande Espresso Frappuccino" , 7.30),
                            ("Grande Signature Hot Chocolate" , 7.20),
                            ("Grande Caramel Hot Chocolate" , 7.80),
                            ("Venti Cold Brew" , 6.30),
                            ("Venti Espresso (Single)" , 4.20),
                            ("Venti Caffe Americano" , 5.70),
                            ("Venti Vanilla Sweet Cream Cold Brew" , 7.80),
                            ("Venti Cold Foam Iced Espresso" , 7.80),
                            ("Venti Cappucino" , 7.10),
                            ("Venti Vanilla Latte" , 7.80),
                            ("Venti Earl Grey" , 7.10),
                            ("Venti English Breakfast" , 7.10),
                            ("Venti Chai" , 7.10),
                            ("Venti Iced Shaken Tea Lemonade" , 6.60),
                            ("Venti Caramel Frappuccino" , 7.80),
                            ("Venti Espresso Frappuccino" , 7.80),
                            ("Venti Signature Hot Chocolate" , 7.70),
                            ("Venti Caramel Hot Chocolate" , 8.30)],

              "lunch":     [("Grande Cold Brew" , 5.80),
                            ("Grande Espresso (Single)" , 3.70),
                            ("Grande Caffe Americano" , 5.20),
                            ("Grande Vanilla Sweet Cream Cold Brew" , 7.30),
                            ("Grande Cold Foam Iced Espresso" , 7.30),
                            ("Grande Cappucino" , 6.60),
                            ("Grande Vanilla Latte" , 7.30),
                            ("Grande Earl Grey" , 6.60),
                            ("Grande English Breakfast" , 6.60),
                            ("Grande Chai" , 6.60),
                            ("Grande Iced Shaken Tea Lemonade" , 6.10),
                            ("Grande Caramel Frappuccino" , 7.30),
                            ("Grande Espresso Frappuccino" , 7.30),
                            ("Grande Signature Hot Chocolate" , 7.20),
                            ("Grande Caramel Hot Chocolate" , 7.80),
                            ("Venti Cold Brew" , 6.30),
                            ("Venti Espresso (Single)" , 4.20),
                            ("Venti Caffe Americano" , 5.70),
                            ("Venti Vanilla Sweet Cream Cold Brew" , 7.80),
                            ("Venti Cold Foam Iced Espresso" , 7.80),
                            ("Venti Cappucino" , 7.10),
                            ("Venti Vanilla Latte" , 7.80),
                            ("Venti Earl Grey" , 7.10),
                            ("Venti English Breakfast" , 7.10),
                            ("Venti Chai" , 7.10),
                            ("Venti Iced Shaken Tea Lemonade" , 6.60),
                            ("Venti Caramel Frappuccino" , 7.80),
                            ("Venti Espresso Frappuccino" , 7.80),
                            ("Venti Signature Hot Chocolate" , 7.70),
                            ("Venti Caramel Hot Chocolate" , 8.30)],

              "dinner":    [("Grande Cold Brew" , 5.80),
                            ("Grande Espresso (Single)" , 3.70),
                            ("Grande Caffe Americano" , 5.20),
                            ("Grande Vanilla Sweet Cream Cold Brew" , 7.30),
                            ("Grande Cold Foam Iced Espresso" , 7.30),
                            ("Grande Cappucino" , 6.60),
                            ("Grande Vanilla Latte" , 7.30),
                            ("Grande Earl Grey" , 6.60),
                            ("Grande English Breakfast" , 6.60),
                            ("Grande Chai" , 6.60),
                            ("Grande Iced Shaken Tea Lemonade" , 6.10),
                            ("Grande Caramel Frappuccino" , 7.30),
                            ("Grande Espresso Frappuccino" , 7.30),
                            ("Grande Signature Hot Chocolate" , 7.20),
                            ("Grande Caramel Hot Chocolate" , 7.80),
                            ("Venti Cold Brew" , 6.30),
                            ("Venti Espresso (Single)" , 4.20),
                            ("Venti Caffe Americano" , 5.70),
                            ("Venti Vanilla Sweet Cream Cold Brew" , 7.80),
                            ("Venti Cold Foam Iced Espresso" , 7.80),
                            ("Venti Cappucino" , 7.10),
                            ("Venti Vanilla Latte" , 7.80),
                            ("Venti Earl Grey" , 7.10),
                            ("Venti English Breakfast" , 7.10),
                            ("Venti Chai" , 7.10),
                            ("Venti Iced Shaken Tea Lemonade" , 6.60),
                            ("Venti Caramel Frappuccino" , 7.80),
                            ("Venti Espresso Frappuccino" , 7.80),
                            ("Venti Signature Hot Chocolate" , 7.70),
                            ("Venti Caramel Hot Chocolate" , 8.30)],

              "closed": [
                           ("This store is not open at this moment.\nWe apologise for any inconvenience caused.", "")
                        ]
        }

can6 = {
              "name" : "Vegetarian Food",
              "day"  : ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
              "halal": True,
              "wtime": [3,3,6],
              "btime": [700, 1159],
              "ltime": [1200, 1429],
              "dtime": [1430, 1700],
              "time" : [700, 1700],
              "breakfast": [("Vegetarian Bee Hoon Set" , 2.80), #monday
                            ("Vegetarian Rice Set" , 2.80),
                            ("White Rice" , 0.50),
                            ("Brown Rice" , 0.80),
                            ("Bee Hoon" , 1.00),
                            ("Fried Rice" , 1.20),
                            ("Vegetable" , 1.00),
                            ("Vegetarian Meat" , 1.20),
                            ("Hor Fun / Crispy Noodle" , 3.00),
                            ("Lo Mee" , 3.00)],

              "lunch":     [("Vegetarian Bee Hoon Set" , 2.80), #every other day
                            ("Vegetarian Rice Set" , 2.80),
                            ("White Rice" , 0.50),
                            ("Brown Rice" , 0.80),
                            ("Bee Hoon" , 1.00),
                            ("Fried Rice" , 1.20),
                            ("Vegetable" , 1.00),
                            ("Vegetarian Meat" , 1.20),
                            ("Hor Fun / Crispy Noodle" , 3.00)],

              "dinner":    [("Vegetarian Bee Hoon Set" , 2.80), #wednesday
                            ("Vegetarian Rice Set" , 2.80),
                            ("White Rice" , 0.50),
                            ("Brown Rice" , 0.80),
                            ("Bee Hoon" , 1.00),
                            ("Fried Rice" , 1.20),
                            ("Vegetable" , 1.00),
                            ("Vegetarian Meat" , 1.20),
                            ("Hor Fun / Crispy Noodle" , 3.00),
                            ("Mee Rebus" , 2.80)],

              "closed": [
                           ("This store is not open at this moment.\nWe apologise for any inconvenience caused.", "")
                        ]
        }
